// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.12
// source: ssc.proto

package sscpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// SSCShardServiceClient is the client API for SSCShardService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SSCShardServiceClient interface {
	// Leader → Members (broadcast), returns signed result
	StartSimulateCXTransaction(ctx context.Context, in *CXTSimulationRequest, opts ...grpc.CallOption) (*CXTSimulationSSCResult, error)
	// Leader → Member, member executes simulation
	HandleSimulateRequest(ctx context.Context, in *CXTSimulationRequest, opts ...grpc.CallOption) (*CXTSimulationResult, error)
	// Member calls back to leader of target shard for cross-shard call
	RequestCallCXT(ctx context.Context, in *CXTCallRequest, opts ...grpc.CallOption) (*CXTCallSSCResult, error)
	// Leader → Member, handle cross-shard call execution
	HandleCXTCall(ctx context.Context, in *CXTCallSSCRequest, opts ...grpc.CallOption) (*CXTCallResult, error)
	// Leader → Members, request BLS signing of a simulation commit
	SignSimulationCommit(ctx context.Context, in *SimulationCommit, opts ...grpc.CallOption) (*Bytes, error)
	SignCXTSimulation(ctx context.Context, in *CXTSimulation, opts ...grpc.CallOption) (*Bytes, error)
	// Member → Leader, submit commit vote
	HandleCommitVote(ctx context.Context, in *CXTCommitVote, opts ...grpc.CallOption) (*Empty, error)
	// Reputation / SL test
	SLTest(ctx context.Context, in *SLTestRequest, opts ...grpc.CallOption) (*SLTestResult, error)
	// Retry pool management
	AddRetryTx(ctx context.Context, in *RetryTx, opts ...grpc.CallOption) (*Empty, error)
	AddToPassivePool(ctx context.Context, in *Hash, opts ...grpc.CallOption) (*Empty, error)
	RetryCommit(ctx context.Context, in *Hash, opts ...grpc.CallOption) (*RetryCommitResp, error)
	RetryCancel(ctx context.Context, in *Hash, opts ...grpc.CallOption) (*Empty, error)
	// Epoch transition
	HandleNewEpoch(ctx context.Context, in *HandleNewEpochRequest, opts ...grpc.CallOption) (*Empty, error)
}

type sSCShardServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSSCShardServiceClient(cc grpc.ClientConnInterface) SSCShardServiceClient {
	return &sSCShardServiceClient{cc}
}

func (c *sSCShardServiceClient) StartSimulateCXTransaction(ctx context.Context, in *CXTSimulationRequest, opts ...grpc.CallOption) (*CXTSimulationSSCResult, error) {
	out := new(CXTSimulationSSCResult)
	err := c.cc.Invoke(ctx, "/sscpb.SSCShardService/StartSimulateCXTransaction", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sSCShardServiceClient) HandleSimulateRequest(ctx context.Context, in *CXTSimulationRequest, opts ...grpc.CallOption) (*CXTSimulationResult, error) {
	out := new(CXTSimulationResult)
	err := c.cc.Invoke(ctx, "/sscpb.SSCShardService/HandleSimulateRequest", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sSCShardServiceClient) RequestCallCXT(ctx context.Context, in *CXTCallRequest, opts ...grpc.CallOption) (*CXTCallSSCResult, error) {
	out := new(CXTCallSSCResult)
	err := c.cc.Invoke(ctx, "/sscpb.SSCShardService/RequestCallCXT", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sSCShardServiceClient) HandleCXTCall(ctx context.Context, in *CXTCallSSCRequest, opts ...grpc.CallOption) (*CXTCallResult, error) {
	out := new(CXTCallResult)
	err := c.cc.Invoke(ctx, "/sscpb.SSCShardService/HandleCXTCall", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sSCShardServiceClient) SignSimulationCommit(ctx context.Context, in *SimulationCommit, opts ...grpc.CallOption) (*Bytes, error) {
	out := new(Bytes)
	err := c.cc.Invoke(ctx, "/sscpb.SSCShardService/SignSimulationCommit", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sSCShardServiceClient) SignCXTSimulation(ctx context.Context, in *CXTSimulation, opts ...grpc.CallOption) (*Bytes, error) {
	out := new(Bytes)
	err := c.cc.Invoke(ctx, "/sscpb.SSCShardService/SignCXTSimulation", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sSCShardServiceClient) HandleCommitVote(ctx context.Context, in *CXTCommitVote, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/sscpb.SSCShardService/HandleCommitVote", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sSCShardServiceClient) SLTest(ctx context.Context, in *SLTestRequest, opts ...grpc.CallOption) (*SLTestResult, error) {
	out := new(SLTestResult)
	err := c.cc.Invoke(ctx, "/sscpb.SSCShardService/SLTest", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sSCShardServiceClient) AddRetryTx(ctx context.Context, in *RetryTx, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/sscpb.SSCShardService/AddRetryTx", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sSCShardServiceClient) AddToPassivePool(ctx context.Context, in *Hash, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/sscpb.SSCShardService/AddToPassivePool", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sSCShardServiceClient) RetryCommit(ctx context.Context, in *Hash, opts ...grpc.CallOption) (*RetryCommitResp, error) {
	out := new(RetryCommitResp)
	err := c.cc.Invoke(ctx, "/sscpb.SSCShardService/RetryCommit", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sSCShardServiceClient) RetryCancel(ctx context.Context, in *Hash, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/sscpb.SSCShardService/RetryCancel", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sSCShardServiceClient) HandleNewEpoch(ctx context.Context, in *HandleNewEpochRequest, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/sscpb.SSCShardService/HandleNewEpoch", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SSCShardServiceServer is the server API for SSCShardService service.
// All implementations must embed UnimplementedSSCShardServiceServer
// for forward compatibility
type SSCShardServiceServer interface {
	// Leader → Members (broadcast), returns signed result
	StartSimulateCXTransaction(context.Context, *CXTSimulationRequest) (*CXTSimulationSSCResult, error)
	// Leader → Member, member executes simulation
	HandleSimulateRequest(context.Context, *CXTSimulationRequest) (*CXTSimulationResult, error)
	// Member calls back to leader of target shard for cross-shard call
	RequestCallCXT(context.Context, *CXTCallRequest) (*CXTCallSSCResult, error)
	// Leader → Member, handle cross-shard call execution
	HandleCXTCall(context.Context, *CXTCallSSCRequest) (*CXTCallResult, error)
	// Leader → Members, request BLS signing of a simulation commit
	SignSimulationCommit(context.Context, *SimulationCommit) (*Bytes, error)
	SignCXTSimulation(context.Context, *CXTSimulation) (*Bytes, error)
	// Member → Leader, submit commit vote
	HandleCommitVote(context.Context, *CXTCommitVote) (*Empty, error)
	// Reputation / SL test
	SLTest(context.Context, *SLTestRequest) (*SLTestResult, error)
	// Retry pool management
	AddRetryTx(context.Context, *RetryTx) (*Empty, error)
	AddToPassivePool(context.Context, *Hash) (*Empty, error)
	RetryCommit(context.Context, *Hash) (*RetryCommitResp, error)
	RetryCancel(context.Context, *Hash) (*Empty, error)
	// Epoch transition
	HandleNewEpoch(context.Context, *HandleNewEpochRequest) (*Empty, error)
	mustEmbedUnimplementedSSCShardServiceServer()
}

// UnimplementedSSCShardServiceServer must be embedded to have forward compatible implementations.
type UnimplementedSSCShardServiceServer struct {
}

func (UnimplementedSSCShardServiceServer) StartSimulateCXTransaction(context.Context, *CXTSimulationRequest) (*CXTSimulationSSCResult, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StartSimulateCXTransaction not implemented")
}
func (UnimplementedSSCShardServiceServer) HandleSimulateRequest(context.Context, *CXTSimulationRequest) (*CXTSimulationResult, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HandleSimulateRequest not implemented")
}
func (UnimplementedSSCShardServiceServer) RequestCallCXT(context.Context, *CXTCallRequest) (*CXTCallSSCResult, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RequestCallCXT not implemented")
}
func (UnimplementedSSCShardServiceServer) HandleCXTCall(context.Context, *CXTCallSSCRequest) (*CXTCallResult, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HandleCXTCall not implemented")
}
func (UnimplementedSSCShardServiceServer) SignSimulationCommit(context.Context, *SimulationCommit) (*Bytes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SignSimulationCommit not implemented")
}
func (UnimplementedSSCShardServiceServer) SignCXTSimulation(context.Context, *CXTSimulation) (*Bytes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SignCXTSimulation not implemented")
}
func (UnimplementedSSCShardServiceServer) HandleCommitVote(context.Context, *CXTCommitVote) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HandleCommitVote not implemented")
}
func (UnimplementedSSCShardServiceServer) SLTest(context.Context, *SLTestRequest) (*SLTestResult, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SLTest not implemented")
}
func (UnimplementedSSCShardServiceServer) AddRetryTx(context.Context, *RetryTx) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddRetryTx not implemented")
}
func (UnimplementedSSCShardServiceServer) AddToPassivePool(context.Context, *Hash) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddToPassivePool not implemented")
}
func (UnimplementedSSCShardServiceServer) RetryCommit(context.Context, *Hash) (*RetryCommitResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RetryCommit not implemented")
}
func (UnimplementedSSCShardServiceServer) RetryCancel(context.Context, *Hash) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RetryCancel not implemented")
}
func (UnimplementedSSCShardServiceServer) HandleNewEpoch(context.Context, *HandleNewEpochRequest) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HandleNewEpoch not implemented")
}
func (UnimplementedSSCShardServiceServer) mustEmbedUnimplementedSSCShardServiceServer() {}

// UnsafeSSCShardServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SSCShardServiceServer will
// result in compilation errors.
type UnsafeSSCShardServiceServer interface {
	mustEmbedUnimplementedSSCShardServiceServer()
}

func RegisterSSCShardServiceServer(s grpc.ServiceRegistrar, srv SSCShardServiceServer) {
	s.RegisterService(&SSCShardService_ServiceDesc, srv)
}

func _SSCShardService_StartSimulateCXTransaction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CXTSimulationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SSCShardServiceServer).StartSimulateCXTransaction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sscpb.SSCShardService/StartSimulateCXTransaction",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SSCShardServiceServer).StartSimulateCXTransaction(ctx, req.(*CXTSimulationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SSCShardService_HandleSimulateRequest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CXTSimulationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SSCShardServiceServer).HandleSimulateRequest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sscpb.SSCShardService/HandleSimulateRequest",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SSCShardServiceServer).HandleSimulateRequest(ctx, req.(*CXTSimulationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SSCShardService_RequestCallCXT_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CXTCallRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SSCShardServiceServer).RequestCallCXT(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sscpb.SSCShardService/RequestCallCXT",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SSCShardServiceServer).RequestCallCXT(ctx, req.(*CXTCallRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SSCShardService_HandleCXTCall_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CXTCallSSCRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SSCShardServiceServer).HandleCXTCall(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sscpb.SSCShardService/HandleCXTCall",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SSCShardServiceServer).HandleCXTCall(ctx, req.(*CXTCallSSCRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SSCShardService_SignSimulationCommit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SimulationCommit)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SSCShardServiceServer).SignSimulationCommit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sscpb.SSCShardService/SignSimulationCommit",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SSCShardServiceServer).SignSimulationCommit(ctx, req.(*SimulationCommit))
	}
	return interceptor(ctx, in, info, handler)
}

func _SSCShardService_SignCXTSimulation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CXTSimulation)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SSCShardServiceServer).SignCXTSimulation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sscpb.SSCShardService/SignCXTSimulation",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SSCShardServiceServer).SignCXTSimulation(ctx, req.(*CXTSimulation))
	}
	return interceptor(ctx, in, info, handler)
}

func _SSCShardService_HandleCommitVote_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CXTCommitVote)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SSCShardServiceServer).HandleCommitVote(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sscpb.SSCShardService/HandleCommitVote",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SSCShardServiceServer).HandleCommitVote(ctx, req.(*CXTCommitVote))
	}
	return interceptor(ctx, in, info, handler)
}

func _SSCShardService_SLTest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SLTestRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SSCShardServiceServer).SLTest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sscpb.SSCShardService/SLTest",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SSCShardServiceServer).SLTest(ctx, req.(*SLTestRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SSCShardService_AddRetryTx_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RetryTx)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SSCShardServiceServer).AddRetryTx(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sscpb.SSCShardService/AddRetryTx",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SSCShardServiceServer).AddRetryTx(ctx, req.(*RetryTx))
	}
	return interceptor(ctx, in, info, handler)
}

func _SSCShardService_AddToPassivePool_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Hash)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SSCShardServiceServer).AddToPassivePool(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sscpb.SSCShardService/AddToPassivePool",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SSCShardServiceServer).AddToPassivePool(ctx, req.(*Hash))
	}
	return interceptor(ctx, in, info, handler)
}

func _SSCShardService_RetryCommit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Hash)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SSCShardServiceServer).RetryCommit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sscpb.SSCShardService/RetryCommit",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SSCShardServiceServer).RetryCommit(ctx, req.(*Hash))
	}
	return interceptor(ctx, in, info, handler)
}

func _SSCShardService_RetryCancel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Hash)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SSCShardServiceServer).RetryCancel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sscpb.SSCShardService/RetryCancel",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SSCShardServiceServer).RetryCancel(ctx, req.(*Hash))
	}
	return interceptor(ctx, in, info, handler)
}

func _SSCShardService_HandleNewEpoch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HandleNewEpochRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SSCShardServiceServer).HandleNewEpoch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sscpb.SSCShardService/HandleNewEpoch",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SSCShardServiceServer).HandleNewEpoch(ctx, req.(*HandleNewEpochRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SSCShardService_ServiceDesc is the grpc.ServiceDesc for SSCShardService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SSCShardService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "sscpb.SSCShardService",
	HandlerType: (*SSCShardServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "StartSimulateCXTransaction",
			Handler:    _SSCShardService_StartSimulateCXTransaction_Handler,
		},
		{
			MethodName: "HandleSimulateRequest",
			Handler:    _SSCShardService_HandleSimulateRequest_Handler,
		},
		{
			MethodName: "RequestCallCXT",
			Handler:    _SSCShardService_RequestCallCXT_Handler,
		},
		{
			MethodName: "HandleCXTCall",
			Handler:    _SSCShardService_HandleCXTCall_Handler,
		},
		{
			MethodName: "SignSimulationCommit",
			Handler:    _SSCShardService_SignSimulationCommit_Handler,
		},
		{
			MethodName: "SignCXTSimulation",
			Handler:    _SSCShardService_SignCXTSimulation_Handler,
		},
		{
			MethodName: "HandleCommitVote",
			Handler:    _SSCShardService_HandleCommitVote_Handler,
		},
		{
			MethodName: "SLTest",
			Handler:    _SSCShardService_SLTest_Handler,
		},
		{
			MethodName: "AddRetryTx",
			Handler:    _SSCShardService_AddRetryTx_Handler,
		},
		{
			MethodName: "AddToPassivePool",
			Handler:    _SSCShardService_AddToPassivePool_Handler,
		},
		{
			MethodName: "RetryCommit",
			Handler:    _SSCShardService_RetryCommit_Handler,
		},
		{
			MethodName: "RetryCancel",
			Handler:    _SSCShardService_RetryCancel_Handler,
		},
		{
			MethodName: "HandleNewEpoch",
			Handler:    _SSCShardService_HandleNewEpoch_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "ssc.proto",
}

// SSCCrossServiceClient is the client API for SSCCrossService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SSCCrossServiceClient interface {
	// Cross-shard: leader → target shard leader, execute SSC call
	HandleCXTSSCCall(ctx context.Context, in *CXTCallSSCRequest, opts ...grpc.CallOption) (*CXTCallSSCResult, error)
	// Cross-shard: commit simulation to related shards
	CommitSimulation(ctx context.Context, in *SimulationCommit, opts ...grpc.CallOption) (*Empty, error)
	// Cross-shard: handle commit SSC vote from another shard
	HandleCXTCommitSSCVote(ctx context.Context, in *CXTCommitSSCVote, opts ...grpc.CallOption) (*Empty, error)
	// Cross-shard: handle commit proof
	HandleCXTCommitProof(ctx context.Context, in *CXTCommitProof, opts ...grpc.CallOption) (*Empty, error)
	// Cross-shard: signal re-simulation
	SignalReSimulation(ctx context.Context, in *RetrySignals, opts ...grpc.CallOption) (*Empty, error)
	// Cross-shard: handle retry signal (with ChainPatch)
	HandleRetrySignal(ctx context.Context, in *RetrySignal, opts ...grpc.CallOption) (*Empty, error)
}

type sSCCrossServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSSCCrossServiceClient(cc grpc.ClientConnInterface) SSCCrossServiceClient {
	return &sSCCrossServiceClient{cc}
}

func (c *sSCCrossServiceClient) HandleCXTSSCCall(ctx context.Context, in *CXTCallSSCRequest, opts ...grpc.CallOption) (*CXTCallSSCResult, error) {
	out := new(CXTCallSSCResult)
	err := c.cc.Invoke(ctx, "/sscpb.SSCCrossService/HandleCXTSSCCall", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sSCCrossServiceClient) CommitSimulation(ctx context.Context, in *SimulationCommit, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/sscpb.SSCCrossService/CommitSimulation", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sSCCrossServiceClient) HandleCXTCommitSSCVote(ctx context.Context, in *CXTCommitSSCVote, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/sscpb.SSCCrossService/HandleCXTCommitSSCVote", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sSCCrossServiceClient) HandleCXTCommitProof(ctx context.Context, in *CXTCommitProof, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/sscpb.SSCCrossService/HandleCXTCommitProof", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sSCCrossServiceClient) SignalReSimulation(ctx context.Context, in *RetrySignals, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/sscpb.SSCCrossService/SignalReSimulation", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sSCCrossServiceClient) HandleRetrySignal(ctx context.Context, in *RetrySignal, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/sscpb.SSCCrossService/HandleRetrySignal", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SSCCrossServiceServer is the server API for SSCCrossService service.
// All implementations must embed UnimplementedSSCCrossServiceServer
// for forward compatibility
type SSCCrossServiceServer interface {
	// Cross-shard: leader → target shard leader, execute SSC call
	HandleCXTSSCCall(context.Context, *CXTCallSSCRequest) (*CXTCallSSCResult, error)
	// Cross-shard: commit simulation to related shards
	CommitSimulation(context.Context, *SimulationCommit) (*Empty, error)
	// Cross-shard: handle commit SSC vote from another shard
	HandleCXTCommitSSCVote(context.Context, *CXTCommitSSCVote) (*Empty, error)
	// Cross-shard: handle commit proof
	HandleCXTCommitProof(context.Context, *CXTCommitProof) (*Empty, error)
	// Cross-shard: signal re-simulation
	SignalReSimulation(context.Context, *RetrySignals) (*Empty, error)
	// Cross-shard: handle retry signal (with ChainPatch)
	HandleRetrySignal(context.Context, *RetrySignal) (*Empty, error)
	mustEmbedUnimplementedSSCCrossServiceServer()
}

// UnimplementedSSCCrossServiceServer must be embedded to have forward compatible implementations.
type UnimplementedSSCCrossServiceServer struct {
}

func (UnimplementedSSCCrossServiceServer) HandleCXTSSCCall(context.Context, *CXTCallSSCRequest) (*CXTCallSSCResult, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HandleCXTSSCCall not implemented")
}
func (UnimplementedSSCCrossServiceServer) CommitSimulation(context.Context, *SimulationCommit) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CommitSimulation not implemented")
}
func (UnimplementedSSCCrossServiceServer) HandleCXTCommitSSCVote(context.Context, *CXTCommitSSCVote) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HandleCXTCommitSSCVote not implemented")
}
func (UnimplementedSSCCrossServiceServer) HandleCXTCommitProof(context.Context, *CXTCommitProof) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HandleCXTCommitProof not implemented")
}
func (UnimplementedSSCCrossServiceServer) SignalReSimulation(context.Context, *RetrySignals) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SignalReSimulation not implemented")
}
func (UnimplementedSSCCrossServiceServer) HandleRetrySignal(context.Context, *RetrySignal) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HandleRetrySignal not implemented")
}
func (UnimplementedSSCCrossServiceServer) mustEmbedUnimplementedSSCCrossServiceServer() {}

// UnsafeSSCCrossServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SSCCrossServiceServer will
// result in compilation errors.
type UnsafeSSCCrossServiceServer interface {
	mustEmbedUnimplementedSSCCrossServiceServer()
}

func RegisterSSCCrossServiceServer(s grpc.ServiceRegistrar, srv SSCCrossServiceServer) {
	s.RegisterService(&SSCCrossService_ServiceDesc, srv)
}

func _SSCCrossService_HandleCXTSSCCall_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CXTCallSSCRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SSCCrossServiceServer).HandleCXTSSCCall(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sscpb.SSCCrossService/HandleCXTSSCCall",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SSCCrossServiceServer).HandleCXTSSCCall(ctx, req.(*CXTCallSSCRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SSCCrossService_CommitSimulation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SimulationCommit)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SSCCrossServiceServer).CommitSimulation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sscpb.SSCCrossService/CommitSimulation",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SSCCrossServiceServer).CommitSimulation(ctx, req.(*SimulationCommit))
	}
	return interceptor(ctx, in, info, handler)
}

func _SSCCrossService_HandleCXTCommitSSCVote_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CXTCommitSSCVote)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SSCCrossServiceServer).HandleCXTCommitSSCVote(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sscpb.SSCCrossService/HandleCXTCommitSSCVote",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SSCCrossServiceServer).HandleCXTCommitSSCVote(ctx, req.(*CXTCommitSSCVote))
	}
	return interceptor(ctx, in, info, handler)
}

func _SSCCrossService_HandleCXTCommitProof_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CXTCommitProof)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SSCCrossServiceServer).HandleCXTCommitProof(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sscpb.SSCCrossService/HandleCXTCommitProof",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SSCCrossServiceServer).HandleCXTCommitProof(ctx, req.(*CXTCommitProof))
	}
	return interceptor(ctx, in, info, handler)
}

func _SSCCrossService_SignalReSimulation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RetrySignals)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SSCCrossServiceServer).SignalReSimulation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sscpb.SSCCrossService/SignalReSimulation",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SSCCrossServiceServer).SignalReSimulation(ctx, req.(*RetrySignals))
	}
	return interceptor(ctx, in, info, handler)
}

func _SSCCrossService_HandleRetrySignal_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RetrySignal)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SSCCrossServiceServer).HandleRetrySignal(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sscpb.SSCCrossService/HandleRetrySignal",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SSCCrossServiceServer).HandleRetrySignal(ctx, req.(*RetrySignal))
	}
	return interceptor(ctx, in, info, handler)
}

// SSCCrossService_ServiceDesc is the grpc.ServiceDesc for SSCCrossService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SSCCrossService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "sscpb.SSCCrossService",
	HandlerType: (*SSCCrossServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "HandleCXTSSCCall",
			Handler:    _SSCCrossService_HandleCXTSSCCall_Handler,
		},
		{
			MethodName: "CommitSimulation",
			Handler:    _SSCCrossService_CommitSimulation_Handler,
		},
		{
			MethodName: "HandleCXTCommitSSCVote",
			Handler:    _SSCCrossService_HandleCXTCommitSSCVote_Handler,
		},
		{
			MethodName: "HandleCXTCommitProof",
			Handler:    _SSCCrossService_HandleCXTCommitProof_Handler,
		},
		{
			MethodName: "SignalReSimulation",
			Handler:    _SSCCrossService_SignalReSimulation_Handler,
		},
		{
			MethodName: "HandleRetrySignal",
			Handler:    _SSCCrossService_HandleRetrySignal_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "ssc.proto",
}

// SSCMonitorServiceClient is the client API for SSCMonitorService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SSCMonitorServiceClient interface {
	GetModuleStatus(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ModuleStatus, error)
}

type sSCMonitorServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSSCMonitorServiceClient(cc grpc.ClientConnInterface) SSCMonitorServiceClient {
	return &sSCMonitorServiceClient{cc}
}

func (c *sSCMonitorServiceClient) GetModuleStatus(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ModuleStatus, error) {
	out := new(ModuleStatus)
	err := c.cc.Invoke(ctx, "/sscpb.SSCMonitorService/GetModuleStatus", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SSCMonitorServiceServer is the server API for SSCMonitorService service.
// All implementations must embed UnimplementedSSCMonitorServiceServer
// for forward compatibility
type SSCMonitorServiceServer interface {
	GetModuleStatus(context.Context, *Empty) (*ModuleStatus, error)
	mustEmbedUnimplementedSSCMonitorServiceServer()
}

// UnimplementedSSCMonitorServiceServer must be embedded to have forward compatible implementations.
type UnimplementedSSCMonitorServiceServer struct {
}

func (UnimplementedSSCMonitorServiceServer) GetModuleStatus(context.Context, *Empty) (*ModuleStatus, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetModuleStatus not implemented")
}
func (UnimplementedSSCMonitorServiceServer) mustEmbedUnimplementedSSCMonitorServiceServer() {}

// UnsafeSSCMonitorServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SSCMonitorServiceServer will
// result in compilation errors.
type UnsafeSSCMonitorServiceServer interface {
	mustEmbedUnimplementedSSCMonitorServiceServer()
}

func RegisterSSCMonitorServiceServer(s grpc.ServiceRegistrar, srv SSCMonitorServiceServer) {
	s.RegisterService(&SSCMonitorService_ServiceDesc, srv)
}

func _SSCMonitorService_GetModuleStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SSCMonitorServiceServer).GetModuleStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sscpb.SSCMonitorService/GetModuleStatus",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SSCMonitorServiceServer).GetModuleStatus(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// SSCMonitorService_ServiceDesc is the grpc.ServiceDesc for SSCMonitorService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SSCMonitorService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "sscpb.SSCMonitorService",
	HandlerType: (*SSCMonitorServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetModuleStatus",
			Handler:    _SSCMonitorService_GetModuleStatus_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "ssc.proto",
}
