package api

import (
	"context"
	"errors"
	"fmt"
	"github.com/ethereum/go-ethereum/common"
	"github.com/harmony-one/harmony/block"
	"github.com/harmony-one/harmony/core/types"
	"math/big"
	"strings"
	"time"
)

var (
	ErrInvalidExecution = errors.New("invalid execution")
)

type SimulationCommitStatus int
type CXTCommitType int
type CXTCommitReason int

const (
	OK SimulationCommitStatus = iota
	ExecutionFailed
)

const (
	Commit CXTCommitType = iota
	Recall
	Rollback
)

const (
	Reason_SUCCESS CXTCommitReason = iota
	Reason_ExecutionFailed
	Reason_InvalidSimulation
	Reason_ConflictRWSet_FailedLock
	Reason_ConflictRWSet_Recall
)

type Epoch uint64

// CallIndex is the index of the cross-shard call
type CallIndex []int

func (c CallIndex) ToString() string {
	return strings.Join(strings.Fields(fmt.Sprint(c)), ":")
}

func FromString(callIndexStr string) CallIndex {
	indexStrs := strings.Split(callIndexStr, ":")
	indexes := make([]int, len(indexStrs))
	for i, indexStr := range indexStrs {
		indexes[i] = int(indexStr[0])
	}
	return indexes
}

// Compare compare each element, if prefix is the same, the longer one is smaller
func (c CallIndex) Compare(other CallIndex) int {
	i := 0
	for i < len(c) && i < len(other) {
		if c[i] != other[i] {
			return c[i] - other[i]
		}
		i++
	}
	return len(other) - len(c)
}

type Config struct {
	CallTimeout              time.Duration
	CXTTimeout               time.Duration
	SimulationCommitGasLimit uint64
	SimulationCommitGasPrice *big.Int
	LockExecutionOnce        bool
}

// Candidate is the candidate of the committee
type Candidate struct {
	Address    common.Address
	Stake      *big.Int
	Reputation uint64
}

// Member is the member of the committee
type Member struct {
	Address  common.Address
	Stake    *big.Int
	Endpoint string
	PubKey   []byte
}

type Validator struct {
	Address common.Address
	PubKey  []byte
}

// ShardSimulateCommittee (SSC) is the committee of the shard simulation
type ShardSimulateCommittee struct {
	ShardID   uint32
	Epoch     Epoch
	Members   []*Member
	Number    int
	Threshold int
}

type SSCMessage struct{}

// CXTSimulationRequest is the request of the cross-shard transaction simulation
type CXTSimulationRequest struct {
	SSCMessage
	Author  *common.Address
	Header  *block.Header
	Tx      *types.Transaction
	GasPool uint64
}

// CXTSimulationResult is the result of the cross-shard transaction simulation
type CXTSimulationResult struct {
	SSCMessage
	RelatedShards []uint32
	Result        []byte
	Receipt       *types.Receipt
	UsedGas       uint64
	Signature     []byte
	Err           error
}

// CXTSimulationSSCResult is CXTSimulationResult with the signature of SSC
type CXTSimulationSSCResult struct {
	SSCMessage
	RelatedShards []uint32
	Result        []byte
	Receipt       *types.Receipt
	UsedGas       uint64
	Signatures    []byte
	Err           error
}

// CXTReSimulationRequest is the request of the cross-shard transaction simulation
type CXTReSimulationRequest struct {
	SSCMessage
	SimulationNum int
	TxHash        []byte
}

// CXTReSimulationResult is the result of the cross-shard transaction simulation
type CXTReSimulationResult struct {
	SSCMessage
	SimulationNum int
	RelatedShards []uint32
	Result        []byte
	Receipt       *types.Receipt
	UsedGas       uint64
	Signature     []byte
	Err           error
}

// CXTReSimulationSSCResult is CXTSimulationResult with the signature of SSC
type CXTReSimulationSSCResult struct {
	SSCMessage
	SimulationNum int
	RelatedShards []uint32
	Result        []byte
	Receipt       *types.Receipt
	UsedGas       uint64
	Signatures    []byte
	Err           error
}

// CXTSimulation is the simulation of the cross-shard transaction
type CXTSimulation struct {
	SSCMessage
	SimulationNum int
	TxHash        []byte
	ShardId       uint32
	OriginShardId uint32
	RelatedShards []uint32
	CallStates    []*CXTCallState // all cross-shard call of cxt related to this shard
	Signatures    []byte
}

// CXTReSimulation is the simulation of the cross-shard transaction
type CXTReSimulation struct {
	SSCMessage
	SimulationNum int
	TxHash        []byte
	ShardId       uint32
	OriginShardId uint32
	RelatedShards []uint32
	RecallStates  []*CXTRecallState // all cross-shard call of cxt related to this shard
	Signatures    []byte
}

// CXTCallState is the state of cross-shard call
type CXTCallState struct {
	CallIndex        CallIndex
	Request          *CXTCallSSCRequest
	RWSet            *RWSet // Read and write set generated by the simulation
	DependentResults []*CXTCallSSCResult
	Result           *CXTCallSSCResult
}

// CXTRecallState is the state of cross-shard Recall
type CXTRecallState struct {
	SimulationNum    int
	CallIndex        CallIndex
	Request          *CXTRecallSSCRequest
	RWSet            *RWSet // Read and write set generated by the simulation
	DependentResults []*CXTRecallSSCResult
	Result           *CXTRecallSSCResult
}

// CXTCallRequest is the request of cross-shard call
type CXTCallRequest struct {
	SSCMessage
	OriginShardId uint32
	FromShardId   uint32
	TargetShardId uint32
	SimulationNum int
	RelatedShards []uint32
	TxHash        []byte
	CallIndex     CallIndex
	Caller        common.Address
	Addr          common.Address
	Input         []byte
	Gas           uint64
	GasPrice      *big.Int
	Value         *big.Int
	Signature     []byte
}

// CXTCallSSCRequest is the request of cross-shard call with the signature of SSC
type CXTCallSSCRequest struct {
	SSCMessage
	OriginShardId uint32
	FromShardId   uint32
	TargetShardId uint32
	SimulationNum int
	RelatedShards []uint32
	TxHash        []byte
	CallIndex     CallIndex
	Caller        common.Address
	Addr          common.Address
	Input         []byte
	Gas           uint64
	GasPrice      *big.Int
	Value         *big.Int
	Signatures    []byte
}

// CXTCallResult is the result of cross-shard call
type CXTCallResult struct {
	SSCMessage
	RelatedShards []uint32
	Result        []byte
	LeftOverGas   uint64
	BlockHash     []byte // block hash of simulation
	Err           error
	Signature     []byte
}

// CXTCallSSCResult is the result of cross-shard call with the signature of SSC
type CXTCallSSCResult struct {
	SSCMessage
	RelatedShards []uint32
	Result        []byte
	LeftOverGas   uint64
	BlockHash     []byte // block hash of simulation
	Err           error
	Signatures    []byte
}

// CXTRecallRequest is the request of cross-shard Recall
type CXTRecallRequest struct {
	SSCMessage
	SimulationNum int
	FromShardId   uint32
	OriginShardId uint32
	TargetShardId uint32
	RelatedShards []uint32
	TxHash        []byte
	CallIndex     CallIndex
	Caller        common.Address
	Addr          common.Address
	Input         []byte
	Gas           uint64
	GasPrice      *big.Int
	Value         *big.Int
	Signature     []byte
}

// CXTRecallSSCRequest is the request of cross-shard Recall with the signature of SSC
type CXTRecallSSCRequest struct {
	SSCMessage
	SimulationNum int
	OriginShardId uint32
	FromShardId   uint32
	TargetShardId uint32
	RelatedShards []uint32
	TxHash        []byte
	CallIndex     CallIndex
	Caller        common.Address
	Addr          common.Address
	Input         []byte
	Gas           uint64
	GasPrice      *big.Int
	Value         *big.Int
	Signatures    []byte
}

// CXTRecallResult is the result of cross-shard recall
type CXTRecallResult struct {
	SSCMessage
	SimulationNum int
	RelatedShards []uint32
	Locked        bool // if the recall lock the state on-chain or re-simulate with rwset
	Result        []byte
	LeftOverGas   uint64
	BlockHash     []byte // block hash of simulation
	Err           error
	Signature     []byte
}

// CXTRecallSSCResult is the result of cross-shard recall with the signature of SSC
type CXTRecallSSCResult struct {
	SSCMessage
	SimulationNum int
	RelatedShards []uint32
	Locked        bool // if the recall lock the state on-chain or re-simulate with rwset
	Result        []byte
	LeftOverGas   uint64
	BlockHash     []byte // block hash of simulation
	Err           error
	Signatures    []byte
}

// SimulationCommit is the used to notify SSC to commit the simulation
type SimulationCommit struct {
	SSCMessage
	SimulationNum int // the number of the simulation
	TxHash        []byte
	RelatedShards []uint32
	Commit        bool
	Status        SimulationCommitStatus
	Signatures    []byte
}

// CXTCommitVote is the vote of the cross-shard transaction commit
type CXTCommitVote struct {
	SSCMessage
	TxHash        []byte
	SimulationNum int // the number of the simulation
	ShardId       uint32
	OriginShardId uint32
	Type          CXTCommitType
	Reason        CXTCommitReason
	Payload       []byte
	Signature     []byte
}

type InvalidSimulationType int

const (
	InvalidSerialization InvalidSimulationType = iota
	InvalidSignature
	InvalidExecution
)

type CXTInvalidSimulationPayload struct {
	Type InvalidSimulationType
}

type CXTConflictRWSetPayload struct {
	ConflictCallIndex CallIndex
}

type CXTExecutionFailedPayload struct {
	Err error
}

// CXTCommitSSCVote is the vote of the cross-shard transaction commit with the signatures of SSC or all nodes
type CXTCommitSSCVote struct {
	SSCMessage
	TxHash        []byte
	SimulationNum int // the number of the simulation
	ShardId       uint32
	OriginShardId uint32
	Type          CXTCommitType
	Reason        CXTCommitReason
	Payload       []byte
	Signatures    []byte
}

type CXTCommitProof struct {
	SSCMessage
	TxHash        []byte
	Type          CXTCommitType
	Reason        CXTCommitReason
	RelatedShards []uint32
	Votes         []*CXTCommitSSCVote
}

type CXTRecallProof struct {
	SSCMessage
	TxHash        []byte
	SimulationNum int // the number of the simulation
	RelatedShards []uint32
	Votes         []*CXTCommitSSCVote
	RecallShards  []uint32
}

type CXTSimulationState struct {
	CallIndex              CallIndex             // current simulation call index
	CurrentIndex           int                   // current index of the simulation call
	SimulationRequest      *CXTSimulationRequest // the simulation request, only origin member has this
	SimulationCallStates   map[int]SimulationCallStates
	SimulationNum          int                            // the number of the simulation used to identify the recall
	LockedCallIndex        CallIndex                      // the locked call index, only the recall after this call index need to be executed
	SimulationRecallStates map[int]SimulationRecallStates // simulationNum -> recallStates
	OriginShardId          uint32
	RelatedShards          []uint32
	RelatedShardMap        map[uint32]struct{}
	TimeoutCtx             context.Context
	TimeoutCancel          context.CancelFunc
}

type SimulationCallStates []*SimulationCallState

func (s SimulationCallStates) Get(index CallIndex) *SimulationCallState {
	for _, state := range s {
		if state.CallIndex.ToString() == index.ToString() {
			return state
		}
	}
	return nil
}

func (s SimulationCallStates) Add(state *SimulationCallState) {
	for i := len(s) - 1; i >= 0; i-- {
		if state.Compare(s[i]) >= 0 {
			s = append(s, nil)
			copy(s[i+1:], s[i:])
			s[i] = state
			return
		}
	}
}

type SimulationCallState struct {
	CallIndex        CallIndex
	Requests         []*CXTCallRequest
	SignedRequest    *CXTCallSSCRequest
	DependentResults []*CXTCallSSCResult
	RWSet            *RWSet
	Result           *CXTCallSSCResult
	Executed         bool
	WaitingChs       []chan *CXTCallSSCResult
}

func (s *SimulationCallState) Compare(other *SimulationCallState) int {
	return s.CallIndex.Compare(other.CallIndex)
}

type ExecutionVerifyState struct {
	Calls map[string]*ExecutionVerifyCall // callIndex -> call
}

type ExecutionVerifyCall struct {
	CallIndex        CallIndex
	Return           []byte
	LeftOverGas      uint64
	CurrentState     *StateSet
	DependentResults []*CXTCallSSCResult
}

type SimulationRecallStates []*SimulationRecallState

func (s SimulationRecallStates) Get(index CallIndex) *SimulationRecallState {
	for _, state := range s {
		if state.CallIndex.ToString() == index.ToString() {
			return state
		}
	}
	return nil
}

func (s SimulationRecallStates) Add(state *SimulationRecallState) {
	for i := len(s) - 1; i >= 0; i-- {
		if state.CallIndex.Compare(s[i].CallIndex) >= 0 {
			s = append(s, nil)
			copy(s[i+1:], s[i:])
			s[i] = state
			return
		}
	}
}

type SimulationRecallState struct {
	CallIndex        CallIndex
	Locked           bool // if the recall lock the state on-chain or re-simulate with rwset
	Requests         []*CXTRecallRequest
	SSCRequest       *CXTRecallSSCRequest
	DependentResults []*CXTRecallSSCResult
	RWSet            *RWSet
	Result           *CXTRecallResult    // the result of simulation self performed
	SSCResult        *CXTRecallSSCResult // the result of simulation from SSC
	Executed         bool
	WaitingChs       []chan *CXTRecallSSCResult
}

type ExecutionVerifyContext struct {
	Simulation       *CXTSimulation
	CallStateMap     map[string]*CXTCallState
	CallIndex        CallIndex
	CurrentIndex     int
	CurrentState     *StateSet
	DependentResults []*CXTCallSSCResult
}

type RWSet struct {
	ReadState    *StateSet
	WriteState   *StateSet
	CurrentState *StateSet
}

type StateSet struct {
	Balance map[common.Address]*big.Int
	State   map[common.Address]map[common.Hash]common.Hash
}

func (s *StateSet) Equal(other *StateSet) bool {
	if len(s.Balance) != len(other.Balance) {
		return false
	}
	for addr, balance := range s.Balance {
		if otherBalance, ok := other.Balance[addr]; !ok || balance.Cmp(otherBalance) != 0 {
			return false
		}
	}
	if len(s.State) != len(other.State) {
		return false
	}
	for addr, state := range s.State {
		if otherState, ok := other.State[addr]; !ok || len(state) != len(otherState) {
			return false
		}
		for key, value := range state {
			if otherValue, ok := other.State[addr][key]; !ok || value != otherValue {
				return false
			}
		}
	}
	return true
}

type CommitState struct {
	CommitVotes    map[int]map[uint32][]*CXTCommitVote  // simulationNum -> shardId -> votes
	CommitSSCVotes map[int]map[uint32]*CXTCommitSSCVote // simulationNum -> shardId -> sscVote
}
